package com.sampurna.pocketmoney.mlm.model

enum class RechargeEnum {

    ADD_MONEY,PAYMENT_HISTORY,WALLET,SHOPPING,
    PREPAID,POSTPAID,DTH,LANDLINE,
    ELECTRICITY,WATER,GAS,BROADBAND,
    LOAN,DMT,LIFE_INSURANCE,FASTAG,
    BANK_TRANSFER,PAYTM_WALLET_TRANSFER,SEND_MONEY,
    GOOGLE_PLAY_RECHARGE,


    STATE,CIRCLE,BOARD
}