package com.sampurna.pocketmoney.mlm.model.serviceModels

data class RechargeHistoryModel(
    val ActionedBy: Double? = null,
    val Circle: Any? = null,
    val CircleCode: Any? = null,
    val ErrorCode: Int? = null,
    val Filter: Any? = null,
    val FromDate: Any? = null,
    val FullName: String? = null,
    val IsComplainRegistered: Boolean? = null,
    val Is_Active: Boolean? = null,
    val MemberID: Double? = null,
    val MobileNo: String? = null,
    val OperatorCode: Any? = null,
    val OperatorProvider: String? = null,
    val OperatorTransID: String? = null,
    val RechargeAmt: Double? = null,
    val Remark: String? = null,
    val RequestDate: String? = null,
    val RequestID: String? = null,
    val ResponseDate: Any? = null,
    val RoleID: Int? = null,
    val ServiceActivated: Boolean? = null,
    val ServiceField1: Any? = null,
    val ServiceField2: Any? = null,
    val ServiceProviderID: Any? = null,
    val ServiceTypeID: Int? = null,
    val Status: String? = null,
    val ToDate: Any? = null,
    val UserID: Double? = null,
    val WalletTypeID: Int? = null,
    val balance: Double? = null
)