package com.example.pocketmoney.utils.myEnums

enum class MyEnums {

OFFERS,SERVICES,SHOPPING,INTRO_IMAGE,DASHBOARD_MENUS,
    FEATURED_PRODUCT,SPECIAL_OFFER,LATEST_PRODUCT,RECOMMENDED_PRODUCT,REVIEW_PRODUCT,DEAL_OF_DAY,FEATURED_BRAND

}


