package com.jmm.model.myEnums

enum class FilterEnum {

    // TIME
    TODAY,YESTERDAY,LAST_WEEK,LAST_MONTH,CUSTOM,
    TOMORROW,THIS_WEEK,THIS_MONTH,LAST_3_MONTH,LAST_6_MONTH,


    POPULAR,NEWEST,PRICE_ASCENDING,PRICE_DESCENDING
}