package com.sampurna.pocketmoney.shopping.model

data class CustomerOrder(
    val BillingAddressId: Int? = null,
    val Discount: Double? = null,
    val GrandTotal: Double? = null,
    val ID: Int? = null,
    val ItemDiscount: Double? = null,
    val OrderDate: String? = null,
    val OrderNumber: String? = null,
    val OrderStatusId: Int? = null,
    val Payment: Double? = null,
    val PaymentMethod: String? = null,
    var PaymentMode: Int? = null,
    var PaymentStatusId: Int? = null,
    val Promo: String? = null,
    val RedeemRewardPointEntryId: Int? = null,
    val RefundedAmount: Double? = null,
    val RewardPointHistoryId: Int? = null,
    val SessionID: String? = null,
    val Shipping: Double? = null,
    val ShippingAddressId: Int? = null,
    val ShippingStatusId: Int? = null,
    val Tax: Double? = null,
    val Token: String? = null,
    val Total: Double? = null,
    val TransactionNumber: String? = null,
    val UserID: String? = null,
    var WalletTypeId: Int? = null
)