package com.example.pocketmoney.mlm.model.mlmModels

import java.io.Serializable

data class CustomerProfileModel(
    val Account: String,
    val AccountName: String,
    val Address1: String,
    val Address2: Any,
    val BankID: Any,
    val BranchName: String,
    val Building: String,
    val BusinessType: String,
    val CityID: Int,
    val CountryID: Any,
    val DOB: Any,
    val District: String,
    val EmailID: String,
    val Filter: Any,
    val FromDate: Any,
    val FullName: String,
    val IFSC: String,
    val IsActive: Boolean,
    val LoginID: Int,
    val Mobile: String,
    val ModifiedBy: Int,
    val ModifiedOn: Any,
    val NomineeID: Int,
    val NomineeName: String,
    val PanCard: String,
    val Password: Any,
    val PersonalDocID: String,
    val PinNo: Any,
    val PinSerialNo: Int,
    val RankID: Int,
    val RankStatus: Int,
    val RegisteredOn: String,
    val Resigned: Boolean,
    val ResignedOn: String,
    val ResignedReason: Any,
    val RoleID: Int,
    val SponsorID: String,
    val SponsorName: String,
    val SponsorNo: Int,
    val StateID: Any,
    val Street: String,
    val ToDate: Any,
    val UserFirstName: Any,
    val UserID: String,
    val UserLastName: Any,
    val UserMiddleName: Any
):Serializable